CREATE TABLE InvoiceDetails(
	LineItemID varchar(30) not NULL,
	LineNo numeric(20, 0) NULL,
	Serial numeric(10, 0) NULL,
	OrderID varchar(30) NULL,
	ClearanceID varchar(30) NULL,
	LotNo numeric(15, 0) NULL,
	LotNo2 numeric(15, 0) NULL,
	ItemCode varchar(15) NULL,
	ItemName varchar(80) NULL,
	LineStatus varchar(1) NULL,
	ItemName2 varchar(80) NULL,
	ImageName varchar(200) NULL,
	ItemDesignCode varchar(20) NULL,
	ItemDesign varchar(40) NULL,
	Quality varchar(80) NULL,
	Brand varchar(40) NULL,
	GroupName varchar(40) NULL,
	AccountGroup varchar(70) NULL,
	ItemColour varchar(80) NULL,
	ItemPattern varchar(30) NULL,
	ItemCategory varchar(40) NULL,
	Size numeric(16, 4) NULL,
	Carton numeric(6, 0) NULL,
	Pack numeric(6, 0) NULL,
	Pcs numeric(8, 2) NULL,
	Meters numeric(12, 4) NULL,
	Fold numeric(6, 2) NULL,
	FoldMtr numeric(8, 2) NULL,
	FoldWt numeric(8, 3) NULL,
	FoldAmt numeric(10, 2) NULL,
	FoldPercent numeric(8, 2) NULL,
	Weight numeric(14, 4) NULL,
	NetWt numeric(12, 3) NULL,
	GrossWt numeric(12, 3) NULL,
	Rate numeric(12, 4) NULL,
	GRate numeric(12, 4) NULL,
	Cost numeric(10, 3) NULL,
	Amount numeric(12, 2) NULL,
	Quantity numeric(10, 2) NULL,
	Comments varchar(1000) NULL,
	AdPerc numeric(6, 2) NULL,
	AdAmt numeric(10, 2) NULL,
	BoxLess numeric(10, 2) NULL,
	DiscPer numeric(6, 2) NULL,
	DiscAmt numeric(10, 2) NULL,
	DiscPer2 numeric(6, 2) NULL,
	DiscAmt2 numeric(10, 2) NULL,
	DiscPer3 numeric(6, 2) NULL,
	DiscAmt3 numeric(10, 2) NULL,
	VatPerc numeric(6, 2) NULL,
	VatAmt numeric(16, 2) NULL,
	CstPerc numeric(6, 2) NULL,
	CstAmt numeric(16, 2) NULL,
	AVatPerc numeric(6, 2) NULL,
	AVatAmt numeric(16, 2) NULL,
	CGSTRate numeric(6, 2) NULL,
	CGSTAmt numeric(16, 2) NULL,
	SGSTRate numeric(6, 2) NULL,
	SGSTAmt numeric(16, 2) NULL,
	IGSTRate numeric(6, 2) NULL,
	IGSTAmt numeric(16, 2) NULL,
	TaxableValue numeric(16, 2) NULL,
	FinalAmt numeric(16, 2) NULL,
	AmtWithoutTax numeric(16, 3) NULL,
	Description1 varchar(999) NULL,
	Description2 varchar(999) NULL,
	BalancePcs numeric(6, 0) NULL,
	BalanceMtrs numeric(8, 2) NULL,
	BalanceWt numeric(15, 3) NULL,
	BoxAmt numeric(16, 2) NULL,
	CutPcs numeric(6, 0) NULL,
	CutMtrs numeric(10, 2) NULL,
	Length numeric(12, 2) NULL,
	Width numeric(12, 2) NULL,
	Thickness numeric(12, 2) NULL,
	ShortPcs numeric(10, 0) NULL,
	ShortMtrs numeric(10, 2) NULL,
	Panna varchar(60) NULL,
	PackRate numeric(10, 2) NULL,
	PackType varchar(40) NULL,
	PackPer varchar(40) NULL,
	PackAmount numeric(10, 2) NULL,
	BaleNo varchar(15) NULL,
	BillPcs numeric(10, 0) NULL,
	BillMtrs numeric(10, 2) NULL,
	BillWt numeric(10, 3) NULL,
	FinPcs numeric(10, 0) NULL,
	FinMtrs numeric(10, 2) NULL,
	FinWt numeric(10, 3) NULL,
	Barcode varchar(25) NULL,
	Catalog varchar(20) NULL,
	Total numeric(10, 2) NULL,
	WastePcs numeric(11, 0) NULL,
	WasteMtrs numeric(11, 2) NULL,
    CreateDate timestamp NULL,
	CreateTime varchar(20) NULL,
    CreatedByID varchar(60) NULL,
PRIMARY KEY (
	LineItemID
)
) 
